import { useState } from 'react';
import { Loader2, Sparkles, Trash2, Users, ChevronDown, ChevronUp } from 'lucide-react';
import type { Persona } from '../lib/persona-pool';
import type { StrategyBrief } from '../lib/strategy-brief';

interface Props {
  readonly personas: readonly Persona[];
  readonly brief: StrategyBrief | null;
  readonly briefIsStale: boolean;
  readonly expanding: boolean;
  readonly expandError: string | null;
  readonly onExpand: (variantsPerSegment: number) => void;
  readonly onToggle: (id: string) => void;
  readonly onRemove: (id: string) => void;
  readonly onClearGenerated: () => void;
}

const sectionStyle = {
  background: 'var(--color-bg-elevated)',
  borderColor: 'var(--color-border-faint)',
} as const;

/**
 * Sheet body for managing the persona pool. Two stacked groups:
 *   1. Core 15 (always-on, non-editable, can be in-session-disabled)
 *   2. Generated sub-personas grouped by source Strategy-Brief segment
 *      with edit/disable/delete affordances + "Expand" button.
 */
export function PersonaPoolView({
  personas,
  brief,
  briefIsStale,
  expanding,
  expandError,
  onExpand,
  onToggle,
  onRemove,
  onClearGenerated,
}: Props) {
  const [variantsCount, setVariantsCount] = useState(7);
  const [coreExpanded, setCoreExpanded] = useState(false);

  const core = personas.filter(p => p.is_core);
  const generated = personas.filter(p => !p.is_core);
  const activeCount = personas.filter(p => p.enabled).length;

  // Group generated by source segment for readability.
  const bySegment = new Map<string, Persona[]>();
  for (const p of generated) {
    const key = p.source_segment_name ?? '(no segment)';
    const arr = bySegment.get(key) ?? [];
    arr.push(p);
    bySegment.set(key, arr);
  }

  const canExpand = brief !== null && !expanding;

  return (
    <div className="flex flex-col gap-4 p-4">
      {/* Header — summary + expand controls */}
      <section
        className="rounded-md border p-3.5 space-y-3"
        style={sectionStyle}
      >
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0">
            <p
              className="font-mono text-[10.5px] tracking-[0.14em] uppercase text-fg-3 inline-flex items-center gap-1.5"
              lang="en"
            >
              <Users className="w-3 h-3" strokeWidth={1.5} aria-hidden="true" />
              Persona Pool
            </p>
            <p className="text-sm font-medium text-fg-1 mt-0.5" lang="th">
              {core.length} core + {generated.length} generated = {personas.length} ใน pool ·
              {' '}
              <span style={{ color: 'var(--color-accent)' }}>{activeCount} active</span>
            </p>
            <p className="text-[11.5px] text-fg-3 mt-1 leading-relaxed" lang="th">
              Judge จะเลือก 4-12 personas ที่เกี่ยวข้องกับ ad นี้จาก pool ด้านล่าง
              {brief
                ? ' · expand จาก Strategy Brief เพื่อแตก segments เป็น sub-personas'
                : ' · สร้าง Strategy Brief ก่อนเพื่อ expand sub-personas เพิ่มได้'}
            </p>
            {briefIsStale && brief && (
              <p
                className="text-[11px] mt-1.5"
                style={{ color: 'var(--color-warning)' }}
                lang="th"
              >
                ⓘ Brief เปลี่ยนตั้งแต่ expand ล่าสุด — re-expand เพื่อให้ pool sync
              </p>
            )}
          </div>
        </div>

        {/* Expand control row */}
        <div className="flex items-center gap-2 flex-wrap">
          <label className="inline-flex items-center gap-1.5 text-[11.5px] text-fg-3" lang="th">
            <span>Variants/segment:</span>
            <input
              type="number"
              min={3}
              max={12}
              value={variantsCount}
              onChange={e => setVariantsCount(Math.max(3, Math.min(12, Number(e.target.value) || 7)))}
              disabled={expanding}
              className="w-14 rounded-md border px-2 py-1 text-fg-1 focus:outline-none disabled:opacity-60"
              style={{
                background: 'var(--color-bg)',
                borderColor: 'var(--color-border-faint)',
              }}
            />
          </label>
          <button
            type="button"
            onClick={() => onExpand(variantsCount)}
            disabled={!canExpand}
            aria-busy={expanding}
            className="inline-flex items-center gap-1.5 text-xs px-3 py-1.5 min-h-[36px] rounded-md border transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            style={{
              background: canExpand
                ? 'color-mix(in oklch, var(--color-accent) 10%, transparent)'
                : 'var(--color-bg)',
              borderColor: 'color-mix(in oklch, var(--color-accent) 35%, transparent)',
              color: 'var(--color-accent)',
            }}
            lang="th"
          >
            {expanding ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" strokeWidth={1.5} aria-hidden="true" />
            ) : (
              <Sparkles className="w-3.5 h-3.5" strokeWidth={1.5} aria-hidden="true" />
            )}
            {expanding ? 'กำลัง expand...' : brief ? 'Expand จาก Strategy Brief' : 'ต้องมี brief ก่อน'}
          </button>
          {generated.length > 0 && (
            <button
              type="button"
              onClick={onClearGenerated}
              disabled={expanding}
              className="inline-flex items-center gap-1.5 text-xs px-3 py-1.5 min-h-[36px] rounded-md border transition-colors hover:bg-bg-hover disabled:opacity-50"
              style={{
                borderColor: 'var(--color-border-faint)',
                color: 'var(--color-fg-3)',
              }}
              lang="th"
            >
              <Trash2 className="w-3.5 h-3.5" strokeWidth={1.5} aria-hidden="true" />
              ล้าง generated ({generated.length})
            </button>
          )}
        </div>

        {expandError && (
          <p
            className="text-[11.5px] leading-relaxed"
            style={{ color: 'var(--color-danger)' }}
            lang="th"
          >
            ⚠ {expandError}
          </p>
        )}
      </section>

      {/* Generated personas — grouped by segment */}
      {generated.length > 0 && (
        <section className="space-y-3">
          <h3
            className="font-mono text-[10.5px] tracking-[0.14em] uppercase text-fg-3"
            lang="en"
          >
            Generated · grouped by segment
          </h3>
          {[...bySegment.entries()].map(([segmentName, list]) => (
            <SegmentGroup
              key={segmentName}
              segmentName={segmentName}
              personas={list}
              onToggle={onToggle}
              onRemove={onRemove}
            />
          ))}
        </section>
      )}

      {/* Core 15 — collapsible */}
      <section
        className="rounded-md border"
        style={sectionStyle}
      >
        <button
          type="button"
          onClick={() => setCoreExpanded(prev => !prev)}
          className="w-full flex items-center justify-between px-3.5 py-2.5 hover:bg-bg-hover transition-colors"
        >
          <span
            className="font-mono text-[10.5px] tracking-[0.14em] uppercase text-fg-3"
            lang="en"
          >
            Core · 15 always-on personas
          </span>
          {coreExpanded ? (
            <ChevronUp className="w-4 h-4 text-fg-3" strokeWidth={1.5} aria-hidden="true" />
          ) : (
            <ChevronDown className="w-4 h-4 text-fg-3" strokeWidth={1.5} aria-hidden="true" />
          )}
        </button>
        {coreExpanded && (
          <ul className="list-none p-0 m-0 space-y-1 px-2 pb-2">
            {core.map(p => (
              <PersonaRow key={p.id} persona={p} onToggle={onToggle} />
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}

interface SegmentGroupProps {
  readonly segmentName: string;
  readonly personas: readonly Persona[];
  readonly onToggle: (id: string) => void;
  readonly onRemove: (id: string) => void;
}

function SegmentGroup({ segmentName, personas, onToggle, onRemove }: SegmentGroupProps) {
  return (
    <div
      className="rounded-md border p-3 space-y-2"
      style={sectionStyle}
    >
      <p
        className="font-mono text-[10.5px] tracking-[0.10em] uppercase"
        style={{ color: 'var(--color-accent)' }}
        lang="th"
      >
        ◆ {segmentName} · {personas.length} variants
      </p>
      <ul className="list-none p-0 m-0 space-y-1">
        {personas.map(p => (
          <PersonaRow key={p.id} persona={p} onToggle={onToggle} onRemove={onRemove} />
        ))}
      </ul>
    </div>
  );
}

interface PersonaRowProps {
  readonly persona: Persona;
  readonly onToggle: (id: string) => void;
  readonly onRemove?: (id: string) => void;
}

function PersonaRow({ persona, onToggle, onRemove }: PersonaRowProps) {
  const dim = !persona.enabled;
  return (
    <li
      className="rounded-md border px-3 py-2 flex items-start gap-3 transition-colors"
      style={{
        background: dim ? 'var(--color-bg-sunken)' : 'var(--color-bg)',
        borderColor: 'var(--color-border-faint)',
        opacity: dim ? 0.55 : 1,
      }}
    >
      <input
        type="checkbox"
        checked={persona.enabled}
        onChange={() => onToggle(persona.id)}
        aria-label={`เปิดปิด persona ${persona.label}`}
        className="mt-1 w-4 h-4 cursor-pointer"
        style={{ accentColor: 'var(--color-accent)' }}
      />
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 flex-wrap">
          <p className="text-[13px] font-medium text-fg-1" lang="th">
            {persona.label}
          </p>
          <code
            className="font-mono text-[10px] px-1.5 py-0.5 rounded text-fg-3"
            style={{ background: 'var(--color-bg-sunken)' }}
          >
            {persona.id}
          </code>
          {persona.is_core && (
            <span
              className="font-mono text-[9.5px] tracking-[0.10em] uppercase px-1.5 py-0.5 rounded"
              style={{
                background: 'color-mix(in oklch, var(--color-info) 10%, transparent)',
                color: 'var(--color-info)',
              }}
            >
              core
            </span>
          )}
        </div>
        <p className="text-[11.5px] text-fg-3 leading-relaxed mt-1" lang="th">
          {persona.description}
        </p>
        {persona.attrs && (
          <div className="flex flex-wrap gap-1.5 mt-1.5">
            {persona.attrs.age_range && (
              <AttrChip label="อายุ" value={persona.attrs.age_range} />
            )}
            {persona.attrs.income_range && (
              <AttrChip label="รายได้" value={persona.attrs.income_range} />
            )}
            {persona.attrs.life_stage && (
              <AttrChip label="ช่วง" value={persona.attrs.life_stage} />
            )}
            {persona.attrs.channel_habit && (
              <AttrChip label="ช่อง" value={persona.attrs.channel_habit} />
            )}
          </div>
        )}
        {persona.attrs?.key_objection && (
          <p
            className="text-[11px] mt-1 italic"
            style={{ color: 'var(--color-fg-3)' }}
            lang="th"
          >
            ข้อกังวล: {persona.attrs.key_objection}
          </p>
        )}
      </div>
      {onRemove && !persona.is_core && (
        <button
          type="button"
          onClick={() => onRemove(persona.id)}
          aria-label={`ลบ persona ${persona.label}`}
          className="inline-flex items-center justify-center min-w-[28px] min-h-[28px] rounded-md text-fg-4 hover:text-fg-1 hover:bg-bg-hover transition-colors"
        >
          <Trash2 className="w-3.5 h-3.5" strokeWidth={1.5} aria-hidden="true" />
        </button>
      )}
    </li>
  );
}

function AttrChip({ label, value }: { readonly label: string; readonly value: string }) {
  return (
    <span
      className="inline-flex items-center gap-1 text-[10px] px-1.5 py-0.5 rounded-pill border"
      style={{
        background: 'var(--color-bg-sunken)',
        borderColor: 'var(--color-border-faint)',
        color: 'var(--color-fg-2)',
      }}
      lang="th"
    >
      <span className="text-fg-4">{label}</span>
      <span>{value}</span>
    </span>
  );
}
